config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :admin_users,
             ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: "manager/home#index"

  namespace :manager do
    resources :citizens, except: :destroy
    get '', to: 'home#index', as: :home
  end

  scope module: :external do
    get '', to: 'home#index', as: :home
    get 'stimulus', to: 'home#stimulus', as: :stimulus
  end
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id           :bigint           not null, primary key
#  cep          :string
#  city         :string
#  complement   :string
#  ibge         :string
#  neighborhood :string
#  street       :string
#  uf           :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  citizen_id   :bigint
#
# Indexes
#
#  index_addresses_on_citizen_id  (citizen_id)
#
class Address < ApplicationRecord
  belongs_to :citizen

  validates :cep, :city, :neighborhood, :street, :uf, presence: true
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_admin_users_on_email                 (email) UNIQUE
#  index_admin_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/citizen.rb
# == Schema Information
#
# Table name: citizens
#
#  id         :bigint           not null, primary key
#  active     :boolean          default(TRUE)
#  birthday   :date
#  cns        :string
#  cpf        :string
#  email      :string
#  full_name  :string
#  phone      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Citizen < ApplicationRecord
  has_one_attached :photo

  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address

  validates :full_name, :cns, :cpf, :email, :birthday, :phone, :photo,
            presence: true
  validates :cpf, cpf: true
  validates :email, email: true
  validates :cns, cns: true
  validates :phone, phone: true
  validates :birthday, birthday: { max_age: 120 }

  after_create :after_create
  before_update :before_update

  def to_s
    full_name
  end

  def after_create
    Senders::Registered.call(self)
  end

  def before_update
    Senders::Changed.call(self)
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/external/home_controller.rb
module External
  class HomeController < ExternalController
    def index; end

    def stimulus; end
  end
end

app/controllers/external_controller.rb
class ExternalController < ApplicationController
  layout 'external'
end

app/controllers/internal_controller.rb
class InternalController < ApplicationController
  layout 'internal'
end

app/controllers/manager/citizens_controller.rb
module Manager
  class CitizensController < InternalController
    before_action :set_citizen,
                  only: %i[show edit update]

    def index
      @q = Citizen.ransack(params[:q])
      @citizens = @q.result(distinct: true)
      @citizens = @citizens.order('created_at').page(params[:page]).per(4)
    end

    def show; end

    def new
      @citizen = Citizen.new
      @citizen.build_address
    end

    def edit
      @citizen.build_address unless @citizen.address
    end

    def create
      @citizen = Citizen.new(citizen_params)
      respond_to do |format|
        if @citizen.save
          format.html do
            redirect_to manager_citizen_path(@citizen),
                        notice: t('controllers.manager.citizens.create')
          end
        else
          format.html do
            render :new,
                   status: :unprocessable_entity
          end
        end
      end
    end

    def update
      respond_to do |format|
        if @citizen.update(citizen_params)
          format.html do
            redirect_to manager_citizen_path(@citizen),
                        notice: t('controllers.manager.citizens.update')
          end
        else
          format.html do
            render :edit,
                   status: :unprocessable_entity
          end
        end
      end
    end

    private

    def set_citizen
      @citizen = Citizen.find(params[:id])
    end

    def citizen_params
      params.require(:citizen).permit(
        :full_name, :cns, :cpf, :email, :birthday, :phone, :active, :photo,
        address_attributes:
          %i[id cep street neighborhood city uf complement ibge]
      )
    end
  end
end

app/controllers/manager/home_controller.rb
module Manager
  class HomeController < InternalController
    def index; end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def convert_to_id(resource)
    resource.to_s.parameterize.concat("-#{resource.id}")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio Jedis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.turbo.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
    <script src="node_modules/flowbite/dist/flowbite.min.js"></script>
  </body>
</html>

app/views/layouts/internal.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Desafio Jedis</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.turbo.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
</head>

<body>

<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="https://flowbite.com/" class="flex items-center">
    </a>
    <div class="flex items-center md:order-2">
      <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
        <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="m17.418 3.623-.018-.008a6.713 6.713 0 0 0-2.4-.569V2h1a1 1 0 1 0 0-2h-2a1 1 0 0 0-1 1v2H9.89A6.977 6.977 0 0 1 12 8v5h-2V8A5 5 0 1 0 0 8v6a1 1 0 0 0 1 1h8v4a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-4h6a1 1 0 0 0 1-1V8a5 5 0 0 0-2.582-4.377ZM6 12H4a1 1 0 0 1 0-2h2a1 1 0 0 1 0 2Z"/>
        </svg>
        <span class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-medium text-blue-800 bg-blue-100 rounded-full dark:bg-blue-900 dark:text-blue-300">3</span>
      </a>
      <button type="button" class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
        <%= image_tag("profile", class: 'w-8 h-8 rounded-full') %>
      </button>
      <!-- Dropdown menu -->
      <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
        <div class="px-4 py-3">
          <span class="block text-sm text-gray-900 dark:text-white">João da Silva</span>
          <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">joaozinhodev@desenvolvendome.com</span>
        </div>
        <ul class="py-2" aria-labelledby="user-menu-button">
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"><%= t('views.layouts.internal.settings') %></a>
          </li>
          <li>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"><%= t('views.layouts.internal.sign_out') %></a>
          </li>
        </ul>
      </div>
      <button type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
        <span class="sr-only"><%= t('views.layouts.sr-only.open_menu') %></span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
      </button>
    </div>
  </div>
</nav>

<aside id="sidebar-multi-level-sidebar" class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
  <div class="h-full px-3 py-4 overflow-y-auto bg-gray-50 dark:bg-gray-800">
    <ul class="space-y-2 font-medium">
      <li>
        <%= link_to manager_home_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" do %>

          <svg class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
            <path d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"/>
            <path d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"/>
          </svg>
          <span class="flex-1 ml-3 whitespace-nowrap"><%= t('views.layouts.internal.dashboard') %></span>
          <span class="bg-purple-100 text-purple-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-purple-900 dark:text-purple-300"><%= t 'views.layouts.internal.new' %></span>
        <% end %>
      </li>
      <li>

      </li>
      <li>
        <button type="button" class="flex items-center w-full p-2 text-base text-gray-900 transition duration-75 rounded-lg group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" aria-controls="dropdown-example" data-collapse-toggle="dropdown-citizen">
          <svg fill="#000000" height="20px" width="20px" version="1.2" baseProfile="tiny" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 256 256" xml:space="preserve">
            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
            <g id="SVGRepo_iconCarrier">
              <path id="XMLID_7_" d="M123.5,127c2.7-2.5,6-3.9,9.4-3.9H251v15.8H136.9c-3.9,0-6,2.2-7.2,3.3c-5,4.7-38.5,35.5-38.5,35.5l-10.1-9.9 C81.1,167.9,118.8,131.4,123.5,127 M191.1,41.1c13.4,0,20.7-9.3,20.7-20.7c0-11.4-9.3-20.7-20.7-20.7c-11.4,0-20.7,9.3-20.7,20.7 C170.4,31.8,179.7,41.1,191.1,41.1 M160.4,76.6h6.9l-10.2,36.5H225l-10.2-36.5h6.9l10.5,36.5h17.9l-14.4-48.4 c-1.9-6.7-10.4-18.5-25-18.5h-39.4c-14.6,0-23.1,11.9-25,18.5L132,113.1h17.9L160.4,76.6z M101.8,111.2L93,94.8l-9.4-17.6 c0,0-1.1-1.6-3.1-0.7c-1.8,0.9-1,2.9-1,2.9l6,11.5l3.8,7.2l-4.3-2c-7.7-3.5-11.9-4.9-13.6-5.7c-0.3-0.1-1.8-1-2.5-2.5 c-2-4.5-10.6-26.2-12.5-31c-1.6-4.1-5.6-9.8-13.9-11.9c-9.4-2.3-18.9,3.6-21.1,13L8.6,112.2c-1.1,4.4-3.1,16.2-3.1,21.1 c0,5,0.1,105.6,0.1,105.6C5.6,247.9,12,255,20.9,255c8.9,0,15-7.3,14.9-16.2c0,0,0-57.5,0-89.5l13.7-57.7c1.6,3.9,3.6,8.7,4.2,9.8 c1.6,2.7,3.1,4.6,6.2,6c0,0,17.9,7.4,24.8,10.6c4.2,1.6,8.7,0.2,11.3-3.1l1-2l0.3,0.6c0,0,2,3.6,5.1,3.8 C103.3,114.5,101.8,111.2,101.8,111.2 M74.1,20.2c0-11.4-9.3-20.7-20.7-20.7C42-0.4,32.8,8.8,32.8,20.2c0,11.4,9.3,20.7,20.7,20.7 C64.9,40.9,74.1,31.7,74.1,20.2 M83.4,155.2l40.3-37.5l-5.2-5.6l-40.3,37.5L83.4,155.2z"></path>
            </g>
          </svg>
          <span class="flex-1 ml-3 text-left whitespace-nowrap">Cadastros</span>
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
          </svg>
        </button>
        <ul id="dropdown-citizen" class="hidden py-2 space-y-2">
          <li>
            <%= link_to manager_citizens_path, class: "flex items-center w-full p-2 text-gray-900 transition duration-75 rounded-lg pl-11 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" do %>
              <svg height="15px" width="15px" version="1.1" id="_x32_" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" xml:space="preserve" fill="#000000">
                <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                <g id="SVGRepo_iconCarrier">
                  <style type="text/css"> .st0 {
                      fill: #000000;
                  } </style>
                  <g>
                    <path class="st0" d="M458.159,404.216c-18.93-33.65-49.934-71.764-100.409-93.431c-28.868,20.196-63.938,32.087-101.745,32.087 c-37.828,0-72.898-11.89-101.767-32.087c-50.474,21.667-81.479,59.782-100.398,93.431C28.731,448.848,48.417,512,91.842,512 c43.426,0,164.164,0,164.164,0s120.726,0,164.153,0C463.583,512,483.269,448.848,458.159,404.216z"></path>
                    <path class="st0" d="M256.005,300.641c74.144,0,134.231-60.108,134.231-134.242v-32.158C390.236,60.108,330.149,0,256.005,0 c-74.155,0-134.252,60.108-134.252,134.242V166.4C121.753,240.533,181.851,300.641,256.005,300.641z"></path>
                  </g>
                </g>
              </svg>
              <span class="flex-1 ml-3 whitespace-nowrap"><%= t('views.layouts.internal.citizen') %></span>
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</aside>

<div class="p-4 sm:ml-64">
  <% if notice.present? %>
    <div id="sticky-banner" tabindex="-1" class="flex justify-between w-full p-4 border-b mb-4
        <%= 'bg-blue-50 text-blue-600 border-blue-200' %>
        <%= 'bg-green-50 text-green-600 border-green-200' if notice.include?('cadastrad') %>
        <%= 'bg-yellow-50 text-yellow-600 border-yellow-200' if notice.include?('atualizad') %>
        <%= 'bg-red-50 text-red-600 border-red-200' if notice.include?('apagad') %>
        dark:border-gray-600">
      <div class="flex items-center mx-auto">
        <!-- Ícone baseado no tipo de mensagem -->
        <% if notice.include?('cadastrad') %>
          <i class="fa fa-circle-plus"></i>
        <% elsif notice.include?('atualizad') %>
          <i class="fa fa-square-pen"></i>
        <% elsif notice.include?('apagad') %>
          <i class="fa fa-trash-can"></i>
        <% else %>
          <i class="fa fa-check-circle"></i>
        <% end %>
        <p class="flex items-center text-sm font-normal ml-2">
          <%= notice %>
        </p>
      </div>
    </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/manager/citizens/_citizen.html.erb
<tr class="border-b dark:border-gray-700" id="<%= dom_id citizen %>">
  <td class="px-4 py-3">
      <%= image_tag citizen.photo.variant(resize_to_limit: [50, 50]), alt: citizen.full_name, class: "rounded-full" %>
  </td>
  <td class="px-4 py-3"> <%= citizen.full_name %></td>
  <td class="px-4 py-3"> <%= citizen.cpf %></td>
  <td class="px-4 py-3"> <%= citizen.cns %></td>
  <td class="px-4 py-3 flex items-center justify-end">
    <button id="<%= convert_to_id(citizen) %>-dropdown-button" data-dropdown-toggle="<%= convert_to_id(citizen) %>-dropdown" class="inline-flex items-center p-0.5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100" type="button">
      <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"/>
      </svg>
    </button>
    <div id="<%= convert_to_id(citizen) %>-dropdown" class="hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
      <% if action_name != "show" %>
        <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="apple-imac-27-dropdown-button">
          <li>
            <%= link_to t('views.manager.citizens.show'), manager_citizen_path(citizen), class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
          </li>
          <li>
            <%= link_to t('views.manager.citizens.edit'), edit_manager_citizen_path(citizen), class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
          </li>
        </ul>
      <% end %>
    </div>
  </td>
</tr>

app/views/manager/citizens/index.html.erb
<section class="bg-gray-50 dark:bg-gray-900 p-3 sm:p-5">
  <div class="mx-auto max-w-screen-xl px-4 lg:px-12">
    <div class="bg-white dark:bg-gray-800 relative shadow-md sm:rounded-lg">
      <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
        <div class="w-full md:w-1/2">
          <%= search_form_for @q, url: manager_citizens_path, method: 'get', class: 'flex' do |f| %>
            <div class="relative w-auto">
              <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"/>
                </svg>
              </div>
            <%= f.search_field :full_name_or_cpf_or_cns_or_email_or_phone_or_address_cep_or_address_city_or_address_street_or_address_uf_or_address_ibge_cont, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500", placeholder: t('views.manager.citizens.index.search') %>
            </div>
            <button type="submit" class="bg-blue-700 text-white rounded-md px-3 py-2 ml-2 hover:bg-primary-600 focus:outline-none focus:ring focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-300">
              <svg aria-hidden="true" class="w-5 h-5 text-white dark:text-white" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"/>
              </svg>
            </button>
          <% end %>
        </div>
        <div class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
          <%= button_to new_manager_citizen_path, method: :get, class: "flex items-center justify-center text-white bg-blue-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800" do %>
            <svg class="h-3.5 w-3.5 mr-2" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <path clip-rule="evenodd" fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z"/>
            </svg>
            <%= t('views.manager.citizens.index.add_citizen') %>
          <% end %>
        </div>
      </div>
      <div class="overflow-x-auto">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-4 py-3"></th>
            <th scope="col" class="px-4 py-3"><%= t('activerecord.attributes.citizen.full_name') %></th>
            <th scope="col" class="px-4 py-3"><%= t('activerecord.attributes.citizen.cpf') %></th>
            <th scope="col" class="px-4 py-3"><%= t('activerecord.attributes.citizen.cns') %></th>
          </tr>
          </thead>
          <tbody>
          <%= render @citizens %>
          </tbody>
        </table>
      </div>
      <nav class="flex flex-col md:flex-row justify-between items-start md:items-center space-y-3 md:space-y-0 p-4" aria-label="Table navigation">
        <span class="text-sm font-normal text-gray-500 dark:text-gray-400">
          <%= page_entries_info @citizens %>
        </span>
        <%= paginate @citizens, window: 1 , outer_window: 1%>
      </nav>
    </div>
  </div>
</section>

app/views/manager/citizens/new.html.erb
<%= simple_form_for @citizen, url: manager_citizens_path,
                    html: { class: 'relative',
                            data: {
                              controller: 'nested-form',
                              nested_form_wrapper_selector_value: '.nested-form-wrapper'
                            } } do |form| %>
  <div class="flex justify-between items-center mb-4">
    <h1 class="font-bold text-4xl"><%= t('views.manager.citizens.index.add_citizen') %></h1>
    <div>
      <%= form.button :submit, t('views.manager.citizens.save'), class: 'cursor-pointer' %>
    </div>
  </div>
  <%= render "form", citizen: @citizen, form: form %>
<% end %>